### PR TITLE
Sprint retrospective

### PR DESCRIPTION
**Pull request by e0426051**
Attempt to implement basic sprint retrospective.

The command syntax are as follows:
retrospective /add -title <title> -id <sprintID> -achievement <what is done well> -improvement <what can improve> -commitment <what to improvements to use for next sprint>
retrospective /del 1 2 3...
retrospective /view 1 2 3...

Todo: Restrict users from adding retrospectives to sprints that are not complete yet

There is possibly a problem with my Json implementation though, if I exit the program and enter again and run retrospective commands immediately, it will nullpointerexception at line: `SprintRetrospective retrospective = proj.getRetrospectiveList().getRetrospective(id);1 or equivalent. Not sure where is the problem, requesting assistance to check what went wrong.

### CODE REVIEW

**Comment by keke101** [comment]
From what I see in your branch's `Project.java`, it might be the case that `toJson` did not include `SprintRetrospectiveManager` data. Hence when the `save` happens, nothing is saved for `SprintRetrospectiveManager` and its sub-objects. So when you reload the program and try to access it, it is empty. You can verify this by inspecting `data/data.json` file to see whether the data for `SprintRetrospectiveManager` is inside.

You can refer to how I did it for `SprintManager`, `ProjectMembers` and `TaskManager`. They should be similar to your class.

**Review by keke101 — CHANGES_REQUESTED** [review]
The operations for saving and parsing the sprint retrospective classes are missing in `Project` class. Without them, the data will always be lost after the program exits.

**Comment by e0426051** [comment]
The basic functionalities are essentially complete(+added removal of corresponding retrospective if a sprint is deleted)

> The operations for saving and parsing the sprint retrospective classes are missing in `Project` class. Without them, the data will always be lost after the program exits.

Thanks for the suggestion.

I have tried to implement the saving of the list into the project class, but now it will cause nullpointerexception when launching scrumptious with the presence of data.json. Any idea what issue this might be? I feel that my tojson and fromjson is very similar if not identical to the ones used in the sprint classes.

Edit: Gradle fail due to failed test classes as a result of nullpointerexception

**Comment by e0426051** [comment]
Addition of the following feature is cancelled.

**Pull request closed without merging**
