### PR TITLE
Added JUnit tests for parser classes

### LINKED ISSUE #192: Complete JUnit
Add JUnit for all relevant parts

- [x] @gmit22 
  - [x] Command
  - [x] Models
- [x] @chocomango  
  - [x] Command
  - [x] Models
- [x] @e0426051  
  - [x] Command
  - [x] Models
- [x] @homingjun  
  - [x] Parser
- [x] @keke101  
  - [x] Command (Clear Storage)
  - [x] Storage Manager
  
* Update the list if you want to be more specific or there are missing elements.  
* **Link this with your PR** if you are doing anything with **JUnit** but don't close it.
* Please proceed to **close this with with your PR** if you are the one **who check the last unchecked checkbox**.

### PR DESCRIPTION
**Pull request by homingjun**
Address some issues in #192

### CODE REVIEW

**Review by keke101 — COMMENTED** [review]
Should we add like positive test cases also? Like those that successfully return the correct command classes if the parsing is successful.

**Comment by homingjun** [comment]
> Should we add like positive test cases also? Like those that successfully return the correct command classes if the parsing is successful.

yea I think it is ok to show successful cases as well

**Review by keke101 — CHANGES_REQUESTED** [review]
`logs/scrum.log.lck` can be ignored, can you add an entry `./logs/*.lck?` in `.gitignore` before we merge?

**Comment by homingjun** [comment]
> `logs/scrum.log.lck` can be ignored, can you add an entry `./logs/*.lck?` in `.gitignore` before we merge?

alright i've added the necessary `.gitignore` changes

**Comment by keke101** [comment]
> > `logs/scrum.log.lck` can be ignored, can you add an entry `./logs/*.lck?` in `.gitignore` before we merge?
> 
> alright i've added the necessary `.gitignore` changes

thanks man

**Review by keke101 — APPROVED** [review]

**Pull request merged**
