### PR TITLE
Sprint v2.0 - Enhancement on existing sprintCommands to work on multiple projects/sprints

### LINKED ISSUE #69: Improvements for Version 2
- Optimize task access using `Hashtable` for `ProjectBacklog` (Refer to #68) 
- Rename sprint action commands for the following
  - Delete task
  - Add task
- `ProjectBacklog` add view command for all tasks
- Change parameters to accept proper data type
  - Move the parsing of the parameters to parser or other relevant functions

### LINKED ISSUE #79: As a user, I would like to be able to view and add task to future sprints

### PR DESCRIPTION
**Pull request by chocomango**

### CODE REVIEW

**Comment by chocomango** [comment]
Apart from updating all the existing SprintCommands, I have changed the ProjectManager to use Hashtable to facilitate the deletion feature of projects in the future.

**Comment by chocomango** [comment]
I have changed the command to allocate task from _/assign_ to _/allocate_ so that I can match the _/deallocate_ command

**Comment by chocomango** [comment]
Will update the user guide soon

**Comment by homingjun** [comment]
Looks good to merge

**Pull request merged**
