### PR TITLE
Attempt to implement TaskRunner into the TaskCommand function.

### PR DESCRIPTION
**Pull request by e0426051**
Not sure if I got this right:

1. I can pass PARAMS(Arraylist of inputs), PARAMETERS(Hashtable of inputs) and rawArgs(String inputs) into the functions.

2. PARAMS, PARAMETERS and rawArgs are inputs by the user and is not used to store the tasks.

2a. The <Task> arraylist will be somewhere else (in the taskCommand function for now)

3. If I use the hashtable, I will also pass in the "final" string constants that are relevant into the function and call the hashtable using those strings from within the function.

4. For commands such as view and done that only takes one integer, I can just send rawArgs into the functions and then parseInt the input.

5. For commands that takes many integers at a time (delete), I can send the PARAMS ArrayList into the function and then use a Integer ArrayList to parseInt the string Arraylist(PARAMS). 

6. For other functions, I pass the HashTable in and then use the get() function to parse the input.

Not sure if I understood/implemented the code correctly. For example for delete should I call rawArgs instead and have another String arraylist to record the numbers? Or should I just pass the Hashtable into the functions and nothing else?

### CODE REVIEW

**Comment by gmit22** [comment]
I think you'll have to pass the project since all of it will be added to the backlog attribute of it. I have implememnted the add and delete, can check from there also if needed.

**Comment by gmit22** [comment]
Code has been changes, the parameters and all so I think you need to adjust to that. So i think need to factor that in

**Comment by keke101** [comment]
`checkStyle` is failing. You should fix them first before you make final commit.

**Comment by e0426051** [comment]
This PR is deprecated. Task function will use Gunit's implementation.

**Pull request closed without merging**
