### PR TITLE
Add support for Sprints

### LINKED ISSUE #16: Create Sprint class with project
Add items from Project Backlog to here, and update accordingly.

### LINKED ISSUE #37: Create Sprint class

### LINKED ISSUE #38: Add command to manipulate the Sprints in the project

### LINKED ISSUE #46: As a user, I can create a Sprint Plan so that I can plan for the new sprint.

### PR DESCRIPTION
**Pull request by chocomango**
Please ignore some testing files

### CODE REVIEW

**Comment by gmit22** [comment]
Any reason for moving project in a different package?

**Comment by chocomango** [comment]
simply to put all data classes in one package, but this is all in development, we can change when we integrate later

**Comment by gmit22** [comment]
Like add all classes which need to be stored in one package?

**Comment by gmit22** [comment]
The structure is making it a bit confusing imo, maybe change that?

**Comment by chocomango** [comment]
I don't understand what you mean by all classes in a file. Maybe we can discuss it during our meeting tonight.

**Comment by gmit22** [comment]
I meant like add all the files whose data has to be stored in the same main package. Also, can you see Duke class and remove your parser?

**Pull request merged**
