### PR TITLE
Task related updates

### PR DESCRIPTION
**Pull request by e0426051**
~~1: Refactored code to change "projectBacklog" variables to "taskList".~~

2: Added help component for Priority View.

3: Fixed JUnit testing for task classes.

### CODE REVIEW

**Comment by gmit22** [comment]
@e0426051 can you check which test cases are failing?

**Comment by gmit22** [comment]
What is this pull request dealing with actually?

**Comment by gmit22** [comment]
May i ask what exactly is the reason beihnd changing all the variables from `backlog` to `tasklist`?

**Comment by e0426051** [comment]
Refactor taskList back to backlog, and use taskList only for the arraylist itself

**Comment by e0426051** [comment]
The messages displayed to user still mentions backlog for clarity

**Review by keke101 — APPROVED** [review]

**Pull request merged**
